name: CrazyBucket
main: powerlated.CrazyBucket
version: 1.0
commands:
  cbkits:
    description: List all kits in Crazy Bucket.
    aliases: [cbk]
    permission: crazybucket.kitpvp
    usage: Just type it.